[package]
name = "just-passwordless"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
lettre = "0.11.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1.4", features = ["sqlite", "r2d2", "chrono"] }
lazy_static = "1.4.0"
rand = "0.8.5"
hex = "0.4.3"
