[package]
name = "just-passwordless"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
lettre = { version = "0.11.4", features = ["rustls-tls", "tokio1-rustls-tls", "builder", "pool", "smtp-transport"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
hex = "0.4.3"
toml = "0.8.10"
chrono = { version = "0.4.35", features = ["serde"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
rand = "0.8.5"
duration-str = "0.7.1"
sqlx = { version = "0.7.3", features = ["sqlx-sqlite", "uuid", "tls-rustls", "chrono", "sqlite", "runtime-tokio"] }
reqwest = { version = "0.11.24", default-features = false, features = ["tokio-rustls", "rustls-tls-webpki-roots"] }
maud = { version = "0.26.0", features = ["actix-web"] }
formatx = "0.2.2"
