# Apart from oidc_clients and users, the following are the default values
# To create a new config, just set the `users` and any other settings you want to change
database_url: database.db

listen_host: 0.0.0.0
listen_port: 8080
path_prefix: /
external_url: http://localhost:8080

link_duration: 1h
session_duration: 1mon

title: MagicEntry

auth_url_enable: true
auth_url_user_header: Remote-User
auth_url_name_header: Remote-Name
auth_url_email_header: Remote-Email
auth_url_realm_header: Remote-Group
auth_url_scopes:
  - origin: http://localhost:8080
    realms:
      - example

oidc_enable: true
oidc_code_duration: 1m
oidc_clients:
  - id: my_client
    secret: my_secret
    redirect_uris:
      - https://openidconnect.net/callback
      - http://127.0.0.1:8081/auth/openid/callback
      - http://localhost:8081/auth/openid/callback
    realms:
      - example

smtp_enable: false
# For the URL scheme options see https://docs.rs/lettre/latest/lettre/transport/smtp/struct.AsyncSmtpTransport.html#method.from_url
smtp_url: smtp://user@pass:localhost:25/?tls=required
smtp_from: "{title} <magicentry@example.com>"
smtp_subject: "{title} Login"
smtp_body: "Click the link to login: {magic_link}"

request_enable: false
request_url: https://www.cinotify.cc/api/notify
request_data: "to={email}&subject={title} Login&body=Click the link to login: <a href=\"{magic_link}\">Login</a>&type=text/html"
request_method: POST
request_content_type: application/x-www-form-urlencoded

webauthn_enable: true

users:
  - username: valid
    name: Valid User
    email: valid@example.com
    realms:
      - example
  - username: integration
    email: valid-integration@example.com
    name: Integration User
    realms:
      - example
      - public
