---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  config.yaml: {{ .Values.config | toYaml | quote }}
