{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.cluster }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}"
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Chart.Name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Chart.Name }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Chart.Name }}"
  apiGroup: rbac.authorization.k8s.io
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Chart.Name }}"
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Chart.Name }}"
  apiGroup: rbac.authorization.k8s.io
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
  annotations: {{ .Values.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end }}
