---

name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        id: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ steps.rust.outputs.cachekey }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Migrate database
        run: |
          sqlx database create
          sqlx migrate run
        env:
          DATABASE_URL: sqlite://database.sqlite3?mode=rwc

      - name: Test
        run: cargo test --release --target ${{ matrix.target }}
        env:
          DATABASE_URL: sqlite://database.sqlite3?mode=rwc
